version: '3.8'
services:

  backend:
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
      target: fast-api-back
    container_name: backend
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./backend:/app

  postgresql-db:
    container_name: db
    image: postgres:14.6
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template
      PGDAT: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres:
